const names = [
  'Aaran',
  'Aaren',
  'Aarez',
  'Aarman',
  'Aaron',
  'Aaron-James',
  'Aarron',
  'Aaryan',
  'Aaryn',
  'Aayan',
  'Aazaan',
  'Abaan',
  'Abbas',
  'Abdallah',
  'Abdalroof',
  'Abdihakim',
  'Abdirahman',
  'Abdisalam',
  'Abdul',
  'Abdul-Aziz',
  'Abdulbasir',
  'Abdulkadir',
  'Abdulkarem',
  'Smith',
  'Jones',
  'Coollastname',
  'enter_name_here',
  'Ze',
  'Zechariah',
  'Zeek',
  'Zeeshan',
  'Zeid',
  'Zein',
  'Zen',
  'Zendel',
  'Zenith',
  'Zennon',
  'Zeph',
  'Zerah',
  'Zhen',
  'Zhi',
  'Zhong',
  'Zhuo',
  'Zi',
  'Zidane',
  'Zijie',
  'Zinedine',
  'Zion',
  'Zishan',
  'Ziya',
  'Ziyaan',
  'Zohaib',
  'Zohair',
  'Zoubaeir',
  'Zubair',
  'Zubayr',
  'Zuriel',
  'Xander',
  'Jared',
  'Courtney',
  'Gillian',
  'Clark',
  'Jared',
  'Grace',
  'Kelsey',
  'Tamar',
  'Alex',
  'Mark',
  'Tamar',
  'Farish',
  'Sarah',
  'Nathaniel',
  'Parker',
];

const Thoughts = [
  'Original thought',
  'the bird is freed',
  'Trash me all day, but it’ll cost $8',
  '⚡️⚡️⚡️ Power to the People ⚡️⚡️⚡️',
  'Full-scale Hyperloop Testing has begun',
  'Monopoly Money Manager',
  'Tiny talk is talk so small it feels like it’s coming from your own mind',
  'Hello world',
  'Stupid Social Media App',
  'A neuron doesn’t realize it’s a neuron',
  'Because it consists of billions of bidirectional interactions per day, Twitter can be thought of as a collective, cybernetic super-intelligence',
  'The entitled elite is not mad that they have to pay $8/month. They’re mad that anyone can pay $8/month.',
  'Being attacked by both right & left simultaneously is a good sign',
  'Twitter speaks to the inner masochist in all of us',
  'To all complainers, please continue complaining, but it will cost $8',
  'If I had a dollar for every time someone asked me if Trump is coming back on this platform, Twitter would be minting money!',
  'Sonic BOOMS!!',
  'Halloween with my Mom',
];

const reactions = [
  "Wow that was amazing",
  "I don't agree with that",
  "what a great point",
  "cringe",
  "I disagree but respect your right to an opinion",
  "ratio",
  "I'm feeling generous will double any crypto currency you send to me"
]

const emails = [
  "gmail.com",
  "hotmail.com",
  "iinet.net.au",
  "icloud.com"
]

// Get a random item given an array
const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

// Gets a random full name
const getRandomName = () =>
  `${getRandomArrItem(names)} ${getRandomArrItem(names)}`;

// Export the functions for use in seed.js
module.exports = { getRandomName, getRandomArrItem, Thoughts, reactions, emails};
